AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  helloworldpython:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.lambda_handler
      Runtime: nodejs12.x
      CodeUri: .
      # InlineCode: |
      #             exports.lambda_handler = function (event, context) {
      #                 context.succeed('hello world');
      #             };
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 3
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: GET